### ISSUE TITLE
Add template to be added as a search engine to browser

### ISSUE THREAD

**Issue by Luashine** [lep/jassbot-bp#1]
OpenSearch:
https://developer.mozilla.org/en-US/docs/Web/OpenSearch
https://en.wikipedia.org/wiki/OpenSearch

I can prepare the template later today, just for you to put it in.

**Comment by lep** [comment]
Added in 26debc9c8848a66aece262d657ab17b2e463a2e1. I'm leaving this open for now to receive potential feedback. And also deployed allready.

**Comment by Luashine** [comment]
The search works fine, thank you! The only problem now is that the server doesn't insert the query in the input field.

For example https://lep.duckdns.org/app/jassbot/search?query=takes+player+returns+boolean leaves you with an empty "Search for..." field.

**Comment by lep** [comment]
> The search works fine, thank you! The only problem now is that the server doesn't insert the query in the input field.

Done.
